# Generated by Django 5.0.4 on 2024-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_tag_alter_author_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_name',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
